variable "tags" {}
variable "env" {}
variable "name" {}
variable "subnets" {}
variable "vpc_id" {}
variable "allow_alb_cidr" {}
variable "internal" {}
variable "listener_priority" {}
variable "dns_name" {}
variable "domain_id" {}